SELECT sign.user_sign,
             sign.employee_no_i,
             sign.signature_icon,
             sign.employee_no,
             sign.firstname,
             sign.lastname,
             sign.description,
             sign.department,
             sign.homebase,
             sign.jobcode,
             sign.jobtitle,
             sign.expire_date,
	TO_CHAR ( DATE '1971-12-31' + sign.birthdate, 'DD.MON.YYYY') AS "BIRTH_DATE",
    TO_CHAR ( DATE '1971-12-31' + sign.entry_date, 'DD.MON.YYYY') AS "JOINING_DATE",
    EXTRACT(YEAR FROM AGE(CURRENT_DATE, DATE '1971-12-31' + sign.entry_date))::INT || ' years ' ||
    EXTRACT(MONTH FROM AGE(CURRENT_DATE, DATE '1971-12-31' + sign.entry_date))::INT || ' months ' ||
    EXTRACT(DAY FROM AGE(CURRENT_DATE, DATE '1971-12-31' + sign.entry_date))::INT || ' days' AS "SENIORITY",
             sign.mech_stamp,
             sign.sex,
             sign.nationality,
             sign.street,
             sign.city,
             sign.country,
             sign.street2,
             sign.city2,
             sign.country2,
             sign.email,
             sign.url_to_pic,
             sign.auth_issue_date,
             sign.auth_expiry_date,
             sign.license_issue_date,
             sign.license_expiry_date
FROM sign  
WHERE sign.user_sign = '@VAR.VJCID@'