SELECT pickslip_detail.progress_status,
       pickslip_detail.pickslipno,
       pickslip_detail.recno,
       pickslip_detail.partno,
       pickslip_detail.serialno,
       pickslip_detail.repair_order,
       pickslip_detail.event_perfno_i,
       pickslip_detail.qty_req,
       pickslip_detail.qty_sys,
       pickslip_detail.qty_booked,
       pickslip_detail.date_booked,
       pickslip_detail.workscope_i,
       pickslip_detail.oddetailno_i,
       pickslip_detail.system_request,
       pickslip_detail.expected_date,
       pickslip_detail.mutation,
       pickslip_detail.mutator,
       pickslip_detail.status,
       pickslip_detail.mutation_time,
       pickslip_detail.created_by,
       pickslip_detail.created_date,
       pickslip_detail.part_requestno_i,
       pickslip_detail.pma_status
FROM pickslip_detail
WHERE pickslip_detail.part_requestno_i = 9345455  
